apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Variable
metadata:
  name: deploy-arn
spec:
  forProvider:
    groupIdRef:
      name: example-group
    variableType: file
    key: AWS_ROLE_ARN
    value: arn:aws:iam::999999999:role/my-deploy-role
  providerConfigRef:
    name: gitlab-provider
