apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Member
metadata:
  name: example-member
spec:
  forProvider:
    groupIdRef:
      name: example-group
    userID: <gitlab-user-id>
    accessLevel: 20
    # expiresAt: "2021-06-09"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-example-member
    namespace: crossplane-system
