---
apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: DeployKey
metadata:
  name: example-deploy-key
  annotations:
spec:
  forProvider:
    projectId: "<example-project-id>"
    title: <example-title>
    canPush: <true or false>
    keySecretRef:
      namespace: <example-name-space>
      name: <example-name>
      key: <example-key>
  providerConfigRef:
    name: <example-provider-config>
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-example-deploy-key
    namespace: crossplane-system
