apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Member
metadata:
  name: example-member
spec:
  forProvider:
    projectIdRef:
      name: example-project
    userID: <gitlab-user-id>
    accessLevel: 30
    # expiresAt: "2021-06-05"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-project-example-member
    namespace: crossplane-system