apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: provider-aws
  annotations:
    crossplane.io/external-name: "cnp/core/provider-aws"
spec:
  forProvider: {}
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: gitlab-project-provider-aws
  providerConfigRef:
    name: gitlab-provider