apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
spec:
  forProvider:
    namespaceId: <GITLAB GROUP ID>
    description: "an example project"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-example-project
    namespace: crossplane-system
