apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: ProjectHook
metadata:
  name: example-project-hook
spec:
  forProvider:
    projectId: 123456
    url: https://example.project.url/hook
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-project-example-projecthook
    namespace: crossplane-system
