name: CI

on:
  push:
    branches:
        - master
  pull_request:
    paths-ignore:
      - '**.md'

env:
  DOCKER_BUILDX_VERSION: 'v0.4.2'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Check Dirty
        run: ./build/run make check-diff

      - name: Vendor Check
        run: ./build/run make vendor.check

      - name: Build
        run: ./build/run make build.all

      - name: Unit Tests
        run: ./build/run make test

      - name: E2E
        run: ./build/run make e2e USE_HELM3=true
